### ISSUE TITLE
지문인식 미지원기기에서 지원유무 확인시 리턴 형식 문제

### ISSUE THREAD

**Issue by blueprajna** [coinstack/cordova-plugin-ios-fingerprint-keychain#1]
지문인식 미지원기기 (iPhone 5, iOS 8.1.2) 에서 
FingerprintKey.isAvailable(function(successes){console.log(successes)},function(error){console.log(error)}) 실행시 리턴값이 {"isAvailable":false}형태로 hasEnrolledFingerprints와 isHardwareDetected 값이 넘오지 않습니다.

**Comment by shepelt** [comment]
해당 버그를 확인했고, 0.1 버젼 릴리즈에 패치 되었습니다.

https://github.com/coinstack/cordova-plugin-ios-fingerprint-keychain/releases/download/0.1/openkeychain-js.zip

에서 src/ios/TouchID.m 파일을 반영해주시면 됩니다.
