### ISSUE TITLE
낮은 iOS 버전에서 코도바 로딩 안됨 

### ISSUE THREAD

**Issue by blueprajna** [coinstack/cordova-plugin-ios-fingerprint-keychain#2]
낮은 iOS 버전(7.1.1)에서 코도바 로딩 중에 멈춤.

**Comment by shepelt** [comment]
혹시 xcode쪽에서 디바이스 로그를 확인할수 있을까요?

구글을 짧게 검색해본 결과 "http://stackoverflow.com/questions/26426461/import-localauthentification-framework-crashes-on-ios-7-1" 이런 글은 있습니다.

이 경우 iOS 7.1에서 localauthentication framework를 로딩하는 바이나리를 실행할시 crash한다는 이야기이고,
해당 글에서는 " 'Project Targets' -> 'Build Phases' -> 'Link Binary with Libraries' -> set LocalAuthentication.framework's status to 'Optional'" 하는 것으로 해결했다고 합니다.

주로 시뮬레이터에서 일어난다는 이야기도 있는데, 장비에 대해서도 확인 부탁드리겠습니다.

**Comment by blueprajna** [comment]
> 이 경우 iOS 7.1에서 localauthentication framework를 로딩하는 바이나리를 실행할시 crash한다는 이야기이고,
> 해당 글에서는 " 'Project Targets' -> 'Build Phases' -> 'Link Binary with Libraries' -> set LocalAuthentication.framework's status to 'Optional'" 하는 것으로 해결했다고 합니다.

optional로 변경해서 해결되었습니다.
