### ISSUE TITLE
TouchID 하드웨어 판정 오류

### ISSUE THREAD

**Issue by blueprajna** [coinstack/cordova-plugin-ios-fingerprint-keychain#3]
isHardwareDetected가 디바이스의 TouchID 지원유무, hasEnrolledFingerprints가 Passcode활성화 되어있고 TouchID까지 활성된걸 말하는거 아닌가요?

isHardwareDetected는 디바이스 모델 값으로 확인해야 하지 않을까요?

**Comment by shepelt** [comment]
hasEnrolledFingerprints 의 경우 지문인식이 활성화 되어 있고, 실제로 등록된 지문이 하나라도 있는 경우를 이야기하고,
isHardwareDetected는 하드웨어, OS에서 지원해서, 지문만 등록하면 사용되는 경우를 나타내고 있습니다.

안드로이드의 경우도 해당 API가 비슷한 의미를 제공하고 있습니다 

https://developer.android.com/reference/android/hardware/fingerprint/FingerprintManager.html#isHardwareDetected()

**Comment by blueprajna** [comment]
현재 코드로 보면 iOS 8.0 이후 버전에서는 에러 코드 별로 디바이스의 지원 유무가 구분되지만 
8.0 이전 버전에서는 모두 isHardwareDetected이 No가 되게 되어 있습니다.
8.0 이전 버전에서도 TouchID 유무를 확인 할수 있어야할것으로 보입니다.
